"""add_turn_records_and_fixes

Revision ID: 4bc7175fd999
Revises: 40070aac3057
Create Date: 2026-01-19 10:16:37.926465

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '4bc7175fd999'
down_revision: Union[str, Sequence[str], None] = '40070aac3057'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('turn_records',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('org_id', sa.String(length=36), nullable=True),
    sa.Column('session_id', sa.String(length=36), nullable=False),
    sa.Column('turn_number', sa.Integer(), nullable=False),
    sa.Column('user_message', sa.Text(), nullable=False),
    sa.Column('npc_response', sa.Text(), nullable=False),
    sa.Column('coach_suggestion', sa.Text(), nullable=True),
    sa.Column('turn_score', sa.Float(), nullable=True),
    sa.Column('fsm_state_before', sa.String(length=50), nullable=False),
    sa.Column('fsm_state_after', sa.String(length=50), nullable=False),
    sa.Column('latency_ms', sa.Float(), nullable=True),
    sa.Column('details', sa.JSON(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['org_id'], ['organizations.id'], ),
    sa.ForeignKeyConstraint(['session_id'], ['sessions.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_turn_records_org_id'), 'turn_records', ['org_id'], unique=False)
    op.create_index(op.f('ix_turn_records_session_id'), 'turn_records', ['session_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_turn_records_session_id'), table_name='turn_records')
    op.drop_index(op.f('ix_turn_records_org_id'), table_name='turn_records')
    op.drop_table('turn_records')
    # ### end Alembic commands ###
