"""Initial migration with Auth and Multi-tenancy

Revision ID: 40070aac3057
Revises: 
Create Date: 2026-01-18 15:16:52.641189

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '40070aac3057'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('organizations',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('slug', sa.String(length=50), nullable=False),
    sa.Column('plan', sa.Enum('FREE', 'PRO', 'TEAM', name='subscriptionplan'), nullable=False),
    sa.Column('subscription_status', sa.String(length=20), nullable=False),
    sa.Column('daily_turns_limit', sa.Integer(), nullable=False),
    sa.Column('daily_turns_used', sa.Integer(), nullable=False),
    sa.Column('quota_reset_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_organizations_slug'), 'organizations', ['slug'], unique=True)
    op.create_table('adoption_records',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('org_id', sa.String(length=36), nullable=True),
    sa.Column('session_id', sa.String(length=36), nullable=False),
    sa.Column('user_id', sa.String(length=36), nullable=False),
    sa.Column('turn_id', sa.Integer(), nullable=False),
    sa.Column('suggestion_id', sa.String(length=36), nullable=False),
    sa.Column('suggestion_text', sa.Text(), nullable=False),
    sa.Column('technique_name', sa.String(length=100), nullable=True),
    sa.Column('adopted', sa.Boolean(), nullable=False),
    sa.Column('adoption_style', sa.Enum('VERBATIM', 'PARAPHRASED', 'STRATEGY_ONLY', 'NOT_ADOPTED', name='adoptionstyle'), nullable=False),
    sa.Column('adoption_evidence', sa.Text(), nullable=True),
    sa.Column('observed_turn_offset', sa.Integer(), nullable=False),
    sa.Column('baseline_scores', sa.JSON(), nullable=False),
    sa.Column('observed_scores', sa.JSON(), nullable=False),
    sa.Column('skill_delta', sa.JSON(), nullable=False),
    sa.Column('is_effective', sa.Boolean(), nullable=False),
    sa.Column('effectiveness_score', sa.Float(), nullable=False),
    sa.Column('stage', sa.String(length=50), nullable=True),
    sa.Column('situation_type', sa.String(length=100), nullable=True),
    sa.Column('strategy_suggested', sa.String(length=100), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['org_id'], ['organizations.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_adoption_records_org_id'), 'adoption_records', ['org_id'], unique=False)
    op.create_index(op.f('ix_adoption_records_session_id'), 'adoption_records', ['session_id'], unique=False)
    op.create_index(op.f('ix_adoption_records_suggestion_id'), 'adoption_records', ['suggestion_id'], unique=False)
    op.create_index(op.f('ix_adoption_records_user_id'), 'adoption_records', ['user_id'], unique=False)
    op.create_table('courses',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('org_id', sa.String(length=36), nullable=True),
    sa.Column('name', sa.String(length=200), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('product_category', sa.String(length=100), nullable=False),
    sa.Column('difficulty_level', sa.String(length=20), nullable=False),
    sa.Column('estimated_duration_minutes', sa.Integer(), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('tags', sa.JSON(), nullable=False),
    sa.Column('prerequisites', sa.JSON(), nullable=False),
    sa.Column('learning_objectives', sa.JSON(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['org_id'], ['organizations.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_courses_name'), 'courses', ['name'], unique=False)
    op.create_index(op.f('ix_courses_org_id'), 'courses', ['org_id'], unique=False)
    op.create_table('sessions',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('org_id', sa.String(length=36), nullable=True),
    sa.Column('user_id', sa.String(length=36), nullable=False),
    sa.Column('course_id', sa.String(length=36), nullable=False),
    sa.Column('scenario_id', sa.String(length=36), nullable=False),
    sa.Column('persona_id', sa.String(length=36), nullable=False),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('started_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('completed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('last_activity_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('total_turns', sa.Integer(), nullable=False),
    sa.Column('total_duration_seconds', sa.Integer(), nullable=False),
    sa.Column('final_score', sa.Float(), nullable=True),
    sa.Column('final_stage', sa.String(length=50), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['org_id'], ['organizations.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_sessions_course_id'), 'sessions', ['course_id'], unique=False)
    op.create_index(op.f('ix_sessions_org_id'), 'sessions', ['org_id'], unique=False)
    op.create_index(op.f('ix_sessions_scenario_id'), 'sessions', ['scenario_id'], unique=False)
    op.create_index(op.f('ix_sessions_status'), 'sessions', ['status'], unique=False)
    op.create_index(op.f('ix_sessions_user_id'), 'sessions', ['user_id'], unique=False)
    op.create_table('strategy_decisions',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('org_id', sa.String(length=36), nullable=True),
    sa.Column('session_id', sa.String(length=36), nullable=False),
    sa.Column('user_id', sa.String(length=36), nullable=False),
    sa.Column('turn_id', sa.Integer(), nullable=False),
    sa.Column('stage', sa.String(length=50), nullable=False),
    sa.Column('situation_type', sa.String(length=100), nullable=False),
    sa.Column('situation_context', sa.Text(), nullable=True),
    sa.Column('strategy_chosen', sa.String(length=100), nullable=False),
    sa.Column('available_strategies', sa.JSON(), nullable=False),
    sa.Column('is_optimal', sa.Boolean(), nullable=False),
    sa.Column('golden_strategy', sa.String(length=100), nullable=False),
    sa.Column('optimality_reason', sa.Text(), nullable=True),
    sa.Column('immediate_score', sa.Float(), nullable=False),
    sa.Column('npc_mood_change', sa.Float(), nullable=False),
    sa.Column('goal_progress', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['org_id'], ['organizations.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_strategy_decisions_org_id'), 'strategy_decisions', ['org_id'], unique=False)
    op.create_index(op.f('ix_strategy_decisions_session_id'), 'strategy_decisions', ['session_id'], unique=False)
    op.create_index(op.f('ix_strategy_decisions_situation_type'), 'strategy_decisions', ['situation_type'], unique=False)
    op.create_index(op.f('ix_strategy_decisions_strategy_chosen'), 'strategy_decisions', ['strategy_chosen'], unique=False)
    op.create_index(op.f('ix_strategy_decisions_user_id'), 'strategy_decisions', ['user_id'], unique=False)
    op.create_table('user_strategy_profiles',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('org_id', sa.String(length=36), nullable=True),
    sa.Column('user_id', sa.String(length=36), nullable=False),
    sa.Column('strategy_frequency', sa.JSON(), nullable=False),
    sa.Column('optimal_rate_by_stage', sa.JSON(), nullable=False),
    sa.Column('optimal_rate_by_situation', sa.JSON(), nullable=False),
    sa.Column('deviation_patterns', sa.JSON(), nullable=False),
    sa.Column('top_weakness_situations', sa.JSON(), nullable=False),
    sa.Column('adoption_rate', sa.Float(), nullable=False),
    sa.Column('effective_adoption_rate', sa.Float(), nullable=False),
    sa.Column('most_effective_techniques', sa.JSON(), nullable=False),
    sa.Column('recommended_focus', sa.JSON(), nullable=False),
    sa.Column('locked_curriculum', sa.JSON(), nullable=False),
    sa.Column('user_override_count', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['org_id'], ['organizations.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_user_strategy_profiles_org_id'), 'user_strategy_profiles', ['org_id'], unique=False)
    op.create_index(op.f('ix_user_strategy_profiles_user_id'), 'user_strategy_profiles', ['user_id'], unique=True)
    op.create_table('users',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('email', sa.String(length=255), nullable=False),
    sa.Column('password_hash', sa.String(length=255), nullable=False),
    sa.Column('full_name', sa.String(length=100), nullable=True),
    sa.Column('role', sa.Enum('ADMIN', 'MANAGER', 'MEMBER', name='userrole'), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('org_id', sa.String(length=36), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['org_id'], ['organizations.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_users_email'), 'users', ['email'], unique=True)
    op.create_table('evaluation_logs',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('session_id', sa.String(length=36), nullable=False),
    sa.Column('turn_number', sa.Integer(), nullable=False),
    sa.Column('overall_score', sa.Float(), nullable=False),
    sa.Column('dimension_scores', sa.JSON(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['session_id'], ['sessions.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_evaluation_logs_session_id'), 'evaluation_logs', ['session_id'], unique=False)
    op.create_table('messages',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('org_id', sa.String(length=36), nullable=True),
    sa.Column('session_id', sa.String(length=36), nullable=False),
    sa.Column('turn_number', sa.Integer(), nullable=False),
    sa.Column('role', sa.String(length=20), nullable=False),
    sa.Column('content', sa.Text(), nullable=False),
    sa.Column('stage', sa.String(length=50), nullable=False),
    sa.Column('intent_result', sa.JSON(), nullable=True),
    sa.Column('npc_result', sa.JSON(), nullable=True),
    sa.Column('coach_result', sa.JSON(), nullable=True),
    sa.Column('evaluator_result', sa.JSON(), nullable=True),
    sa.Column('rag_result', sa.JSON(), nullable=True),
    sa.Column('compliance_result', sa.JSON(), nullable=True),
    sa.Column('turn_score', sa.Float(), nullable=True),
    sa.Column('dimension_scores', sa.JSON(), nullable=True),
    sa.Column('processing_time_ms', sa.Float(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['org_id'], ['organizations.id'], ),
    sa.ForeignKeyConstraint(['session_id'], ['sessions.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_messages_org_id'), 'messages', ['org_id'], unique=False)
    op.create_index(op.f('ix_messages_session_id'), 'messages', ['session_id'], unique=False)
    op.create_table('scenario_configs',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('org_id', sa.String(length=36), nullable=True),
    sa.Column('course_id', sa.String(length=36), nullable=False),
    sa.Column('name', sa.String(length=200), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('product_category', sa.String(length=100), nullable=False),
    sa.Column('scenario_background', sa.Text(), nullable=True),
    sa.Column('sales_goal', sa.Text(), nullable=True),
    sa.Column('success_criteria', sa.JSON(), nullable=False),
    sa.Column('stage_configs', sa.JSON(), nullable=False),
    sa.Column('max_turns', sa.Integer(), nullable=False),
    sa.Column('difficulty_level', sa.String(length=20), nullable=False),
    sa.Column('customer_difficulty', sa.Float(), nullable=False),
    sa.Column('required_level', sa.Integer(), nullable=False),
    sa.Column('prerequisite_skills', sa.JSON(), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['course_id'], ['courses.id'], ),
    sa.ForeignKeyConstraint(['org_id'], ['organizations.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_scenario_configs_course_id'), 'scenario_configs', ['course_id'], unique=False)
    op.create_index(op.f('ix_scenario_configs_org_id'), 'scenario_configs', ['org_id'], unique=False)
    op.create_table('session_states',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('session_id', sa.String(length=36), nullable=False),
    sa.Column('current_stage', sa.String(length=50), nullable=False),
    sa.Column('stage_history', sa.JSON(), nullable=False),
    sa.Column('slot_values', sa.JSON(), nullable=False),
    sa.Column('stage_coverages', sa.JSON(), nullable=False),
    sa.Column('goal_achieved', sa.JSON(), nullable=False),
    sa.Column('npc_mood', sa.Float(), nullable=False),
    sa.Column('turn_count', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['session_id'], ['sessions.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_session_states_session_id'), 'session_states', ['session_id'], unique=True)
    op.create_table('customer_personas',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('org_id', sa.String(length=36), nullable=True),
    sa.Column('scenario_id', sa.String(length=36), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('occupation', sa.String(length=100), nullable=True),
    sa.Column('age_range', sa.String(length=20), nullable=True),
    sa.Column('gender', sa.String(length=10), nullable=True),
    sa.Column('personality_traits', sa.Text(), nullable=True),
    sa.Column('communication_style', sa.String(length=100), nullable=True),
    sa.Column('decision_style', sa.String(length=100), nullable=True),
    sa.Column('buying_motivation', sa.Text(), nullable=True),
    sa.Column('main_concerns', sa.Text(), nullable=True),
    sa.Column('budget_sensitivity', sa.String(length=50), nullable=True),
    sa.Column('initial_mood', sa.Float(), nullable=False),
    sa.Column('mood_volatility', sa.Float(), nullable=False),
    sa.Column('difficulty_level', sa.String(length=20), nullable=False),
    sa.Column('objection_frequency', sa.Float(), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['org_id'], ['organizations.id'], ),
    sa.ForeignKeyConstraint(['scenario_id'], ['scenario_configs.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_customer_personas_org_id'), 'customer_personas', ['org_id'], unique=False)
    op.create_index(op.f('ix_customer_personas_scenario_id'), 'customer_personas', ['scenario_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_customer_personas_scenario_id'), table_name='customer_personas')
    op.drop_index(op.f('ix_customer_personas_org_id'), table_name='customer_personas')
    op.drop_table('customer_personas')
    op.drop_index(op.f('ix_session_states_session_id'), table_name='session_states')
    op.drop_table('session_states')
    op.drop_index(op.f('ix_scenario_configs_org_id'), table_name='scenario_configs')
    op.drop_index(op.f('ix_scenario_configs_course_id'), table_name='scenario_configs')
    op.drop_table('scenario_configs')
    op.drop_index(op.f('ix_messages_session_id'), table_name='messages')
    op.drop_index(op.f('ix_messages_org_id'), table_name='messages')
    op.drop_table('messages')
    op.drop_index(op.f('ix_evaluation_logs_session_id'), table_name='evaluation_logs')
    op.drop_table('evaluation_logs')
    op.drop_index(op.f('ix_users_email'), table_name='users')
    op.drop_table('users')
    op.drop_index(op.f('ix_user_strategy_profiles_user_id'), table_name='user_strategy_profiles')
    op.drop_index(op.f('ix_user_strategy_profiles_org_id'), table_name='user_strategy_profiles')
    op.drop_table('user_strategy_profiles')
    op.drop_index(op.f('ix_strategy_decisions_user_id'), table_name='strategy_decisions')
    op.drop_index(op.f('ix_strategy_decisions_strategy_chosen'), table_name='strategy_decisions')
    op.drop_index(op.f('ix_strategy_decisions_situation_type'), table_name='strategy_decisions')
    op.drop_index(op.f('ix_strategy_decisions_session_id'), table_name='strategy_decisions')
    op.drop_index(op.f('ix_strategy_decisions_org_id'), table_name='strategy_decisions')
    op.drop_table('strategy_decisions')
    op.drop_index(op.f('ix_sessions_user_id'), table_name='sessions')
    op.drop_index(op.f('ix_sessions_status'), table_name='sessions')
    op.drop_index(op.f('ix_sessions_scenario_id'), table_name='sessions')
    op.drop_index(op.f('ix_sessions_org_id'), table_name='sessions')
    op.drop_index(op.f('ix_sessions_course_id'), table_name='sessions')
    op.drop_table('sessions')
    op.drop_index(op.f('ix_courses_org_id'), table_name='courses')
    op.drop_index(op.f('ix_courses_name'), table_name='courses')
    op.drop_table('courses')
    op.drop_index(op.f('ix_adoption_records_user_id'), table_name='adoption_records')
    op.drop_index(op.f('ix_adoption_records_suggestion_id'), table_name='adoption_records')
    op.drop_index(op.f('ix_adoption_records_session_id'), table_name='adoption_records')
    op.drop_index(op.f('ix_adoption_records_org_id'), table_name='adoption_records')
    op.drop_table('adoption_records')
    op.drop_index(op.f('ix_organizations_slug'), table_name='organizations')
    op.drop_table('organizations')
    # ### end Alembic commands ###
